utils::globalVariables("mapping")
utils::globalVariables("available.providers")
utils::globalVariables("available.costmethods")
# utils::globalVariables("mort")
# utils::globalVariables("probDeath")
# utils::globalVariables("probDeathCause")
# utils::globalVariables("probDeathChapters")
# utils::globalVariables("ratios")
# utils::globalVariables("scdc")
